In [1]:
#Step 3: Optimize Data

#Attempt #1: add back in EIN

In [2]:
#import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#import and read csv
import pandas as pd
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
#drop the non-beneficial ID columns, 'EIN' and "NAME"
application_df = application_df.drop(columns=["NAME"])
application_df.head()

,EIN,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
#determine the number of unique values in each column

#create categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes =="object"].index.tolist()

#check the number of unique values in each column
application_df[application_cat].nunique()

APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
ORGANIZATION               4
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
dtype: int64

In [5]:
#look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
#choose a cutoff value and create a list of application types to be replaced 
#use the variable name 'application_types_to_replace'
application_types_to_replace = list(application_type_counts[application_type_counts<500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [7]:
#replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

#check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# look at CLASSIFICATION value counts >1
cleaned_class_counts = classification_counts[classification_counts > 1]
cleaned_class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
#choose a cutoff value and create a list of classifications to be replaced
#use the variable name 'classifications_to_replace'
classifications_to_replace = list(cleaned_class_counts[cleaned_class_counts<100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256']

In [11]:
#replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")
    
#make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      643
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: CLASSIFICATION, dtype: int64

In [12]:
#convert categorical data to numeric data with 'pd.get_dummies'
application_df = pd.get_dummies(application_df, dtype=float)
application_df

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,10531628,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,10547893,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,10553066,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,10556103,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,996010315,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,996012607,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,996015768,1,5000,1,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,996086871,1,36500179,0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [13]:
#split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"], 1).values

#split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

C:\Users\jenna\AppData\Local\Temp/ipykernel_19864/3545267911.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = application_df.drop(["IS_SUCCESSFUL"], 1).values

In [14]:
#create a StandardScaler instances
scaler = StandardScaler()

#fit the StandardScaler
X_scaler = scaler.fit(X_train)

#Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [15]:
#define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

#first hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

#second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

#output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

#check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 616
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 667
Trainable params: 667
Non-trainable params: 0
_________________________________________________________________

In [16]:
#compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
#train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6221 - accuracy: 0.6886
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5637 - accuracy: 0.7290
Epoch 3/100
804/804 [==============================] - 1s 983us/step - loss: 0.5540 - accuracy: 0.7325
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7327
Epoch 5/100
804/804 [==============================] - 1s 924us/step - loss: 0.5486 - accuracy: 0.7331
Epoch 6/100
804/804 [==============================] - 1s 908us/step - loss: 0.5474 - accuracy: 0.7340
Epoch 7/100
804/804 [==============================] - 1s 913us/step - loss: 0.5465 - accuracy: 0.7335
Epoch 8/100
804/804 [==============================] - 1s 889us/step - loss: 0.5454 - accuracy: 0.7348
Epoch 9/100
804/804 [==============================] - 1s 931us/step - loss: 0.5449 - accuracy: 0.7354
Epoch 10/100
804/804 [==============================] - 1s 907us/step - loss: 0.5446 - accuracy: 0.7348
Epoch 11/100
804/804 [==============================] - 1s 910us/step - loss: 0.5439 - accuracy: 0.7360
Epoch 12/100
804/804 [==============================] - 1s 915us/step - loss: 0.5439 - accuracy: 0.7352
Epoch 13/100
804/804 [==============================] - 1s 901us/step - loss: 0.5435 - accuracy: 0.7364
Epoch 14/100
804/804 [==============================] - 1s 924us/step - loss: 0.5432 - accuracy: 0.7359
Epoch 15/100
804/804 [==============================] - 1s 914us/step - loss: 0.5427 - accuracy: 0.7362
Epoch 16/100
804/804 [==============================] - 1s 918us/step - loss: 0.5424 - accuracy: 0.7360
Epoch 17/100
804/804 [==============================] - 1s 924us/step - loss: 0.5425 - accuracy: 0.7363
Epoch 18/100
804/804 [==============================] - 1s 900us/step - loss: 0.5422 - accuracy: 0.7360
Epoch 19/100
804/804 [==============================] - 1s 865us/step - loss: 0.5417 - accuracy: 0.7368
Epoch 20/100
804/804 [==============================] - 1s 915us/step - loss: 0.5413 - accuracy: 0.7356
Epoch 21/100
804/804 [==============================] - 1s 981us/step - loss: 0.5411 - accuracy: 0.7350
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7351
Epoch 23/100
804/804 [==============================] - 1s 950us/step - loss: 0.5407 - accuracy: 0.7360
Epoch 24/100
804/804 [==============================] - 1s 904us/step - loss: 0.5404 - accuracy: 0.7359
Epoch 25/100
804/804 [==============================] - 1s 896us/step - loss: 0.5405 - accuracy: 0.7360
Epoch 26/100
804/804 [==============================] - 1s 931us/step - loss: 0.5402 - accuracy: 0.7364
Epoch 27/100
804/804 [==============================] - 1s 920us/step - loss: 0.5402 - accuracy: 0.7361
Epoch 28/100
804/804 [==============================] - 1s 999us/step - loss: 0.5398 - accuracy: 0.7361
Epoch 29/100
804/804 [==============================] - 1s 932us/step - loss: 0.5400 - accuracy: 0.7365
Epoch 30/100
804/804 [==============================] - 1s 913us/step - loss: 0.5397 - accuracy: 0.7365
Epoch 31/100
804/804 [==============================] - 1s 914us/step - loss: 0.5396 - accuracy: 0.7365
Epoch 32/100
804/804 [==============================] - 1s 919us/step - loss: 0.5396 - accuracy: 0.7362
Epoch 33/100
804/804 [==============================] - 1s 928us/step - loss: 0.5396 - accuracy: 0.7369
Epoch 34/100
804/804 [==============================] - 1s 928us/step - loss: 0.5392 - accuracy: 0.7363
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7370
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7374
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7367
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7370
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7367
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7377
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7370
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7374
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7371
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7380
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7374
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7372
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7370
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7365
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7379
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7371
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7376
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7367
Epoch 53/100
804/804 [==============================] - 1s 880us/step - loss: 0.5379 - accuracy: 0.7379
Epoch 54/100
804/804 [==============================] - 1s 870us/step - loss: 0.5373 - accuracy: 0.7378
Epoch 55/100
804/804 [==============================] - 1s 962us/step - loss: 0.5372 - accuracy: 0.7372
Epoch 56/100
804/804 [==============================] - 1s 896us/step - loss: 0.5372 - accuracy: 0.7372
Epoch 57/100
804/804 [==============================] - 1s 847us/step - loss: 0.5371 - accuracy: 0.7383
Epoch 58/100
804/804 [==============================] - 1s 903us/step - loss: 0.5377 - accuracy: 0.7379
Epoch 59/100
804/804 [==============================] - 1s 919us/step - loss: 0.5370 - accuracy: 0.7383
Epoch 60/100
804/804 [==============================] - 1s 938us/step - loss: 0.5373 - accuracy: 0.7374
Epoch 61/100
804/804 [==============================] - 1s 915us/step - loss: 0.5373 - accuracy: 0.7380
Epoch 62/100
804/804 [==============================] - 1s 919us/step - loss: 0.5369 - accuracy: 0.7386
Epoch 63/100
804/804 [==============================] - 1s 913us/step - loss: 0.5373 - accuracy: 0.7373
Epoch 64/100
804/804 [==============================] - 1s 946us/step - loss: 0.5370 - accuracy: 0.7379
Epoch 65/100
804/804 [==============================] - 1s 979us/step - loss: 0.5370 - accuracy: 0.7382
Epoch 66/100
804/804 [==============================] - 1s 963us/step - loss: 0.5370 - accuracy: 0.7383
Epoch 67/100
804/804 [==============================] - 1s 921us/step - loss: 0.5371 - accuracy: 0.7383
Epoch 68/100
804/804 [==============================] - 1s 916us/step - loss: 0.5368 - accuracy: 0.7369
Epoch 69/100
804/804 [==============================] - 1s 929us/step - loss: 0.5369 - accuracy: 0.7373
Epoch 70/100
804/804 [==============================] - 1s 941us/step - loss: 0.5368 - accuracy: 0.7367
Epoch 71/100
804/804 [==============================] - 1s 933us/step - loss: 0.5367 - accuracy: 0.7376
Epoch 72/100
804/804 [==============================] - 1s 906us/step - loss: 0.5368 - accuracy: 0.7378
Epoch 73/100
804/804 [==============================] - 1s 923us/step - loss: 0.5369 - accuracy: 0.7367
Epoch 74/100
804/804 [==============================] - 1s 916us/step - loss: 0.5367 - accuracy: 0.7383
Epoch 75/100
804/804 [==============================] - 1s 920us/step - loss: 0.5368 - accuracy: 0.7381
Epoch 76/100
804/804 [==============================] - 1s 919us/step - loss: 0.5369 - accuracy: 0.7374
Epoch 77/100
804/804 [==============================] - 1s 904us/step - loss: 0.5367 - accuracy: 0.7386
Epoch 78/100
804/804 [==============================] - 1s 920us/step - loss: 0.5367 - accuracy: 0.7378
Epoch 79/100
804/804 [==============================] - 1s 892us/step - loss: 0.5366 - accuracy: 0.7371
Epoch 80/100

804/804 [==============================] - 1s 886us/step - loss: 0.5369 - accuracy: 0.7383
Epoch 81/100
804/804 [==============================] - 1s 872us/step - loss: 0.5365 - accuracy: 0.7383
Epoch 82/100
804/804 [==============================] - 1s 872us/step - loss: 0.5366 - accuracy: 0.7376
Epoch 83/100
804/804 [==============================] - 1s 864us/step - loss: 0.5368 - accuracy: 0.7381
Epoch 84/100
804/804 [==============================] - 1s 861us/step - loss: 0.5368 - accuracy: 0.7383
Epoch 85/100
804/804 [==============================] - 1s 862us/step - loss: 0.5363 - accuracy: 0.7377
Epoch 86/100
804/804 [==============================] - 1s 891us/step - loss: 0.5365 - accuracy: 0.7375
Epoch 87/100
804/804 [==============================] - 1s 903us/step - loss: 0.5366 - accuracy: 0.7379
Epoch 88/100
804/804 [==============================] - 1s 962us/step - loss: 0.5363 - accuracy: 0.7381
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7377
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7374
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7385
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7379
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7381
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7382
Epoch 95/100
804/804 [==============================] - 1s 961us/step - loss: 0.5363 - accuracy: 0.7378
Epoch 96/100
804/804 [==============================] - 1s 955us/step - loss: 0.5360 - accuracy: 0.7385
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5359 - accuracy: 0.7378
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7380
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7384
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7372

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5462 - accuracy: 0.7275
Loss: 0.5462350249290466, Accuracy: 0.7274635434150696

In [19]:
#Attempt #2: Add number of epochs to the training regimen


#import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#import and read csv
import pandas as pd
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [20]:
#drop the non-beneficial ID columns, 'EIN' and "NAME"
application_df = application_df.drop(columns=["NAME"])
application_df = application_df.drop(columns =["EIN"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [21]:
#determine the number of unique values in each column

#create categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes =="object"].index.tolist()

#check the number of unique values in each column
application_df[application_cat].nunique()

APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
ORGANIZATION               4
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
dtype: int64

In [22]:
#look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [23]:
#choose a cutoff value and create a list of application types to be replaced 
#use the variable name 'application_types_to_replace'
application_types_to_replace = list(application_type_counts[application_type_counts<500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [24]:
#replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

#check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [25]:
# look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [26]:
# look at CLASSIFICATION value counts >1
cleaned_class_counts = classification_counts[classification_counts > 1]
cleaned_class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [27]:
#choose a cutoff value and create a list of classifications to be replaced
#use the variable name 'classifications_to_replace'
classifications_to_replace = list(cleaned_class_counts[cleaned_class_counts<100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256']

In [28]:
#replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")
    
#make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      643
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: CLASSIFICATION, dtype: int64

In [29]:
#convert categorical data to numeric data with 'pd.get_dummies'
application_df = pd.get_dummies(application_df, dtype=float)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [30]:
#split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"], 1).values

#split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

C:\Users\jenna\AppData\Local\Temp/ipykernel_19864/3545267911.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = application_df.drop(["IS_SUCCESSFUL"], 1).values

In [31]:
#create a StandardScaler instances
scaler = StandardScaler()

#fit the StandardScaler
X_scaler = scaler.fit(X_train)

#Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [32]:
#define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

#first hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

#second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

#output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

#check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 8)                 608
_________________________________________________________________
dense_4 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 6
=================================================================
Total params: 659
Trainable params: 659
Non-trainable params: 0
_________________________________________________________________

In [33]:
#compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [34]:
#train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=500)

Epoch 1/500
804/804 [==============================] - 1s 1ms/step - loss: 0.6107 - accuracy: 0.6904
Epoch 2/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5626 - accuracy: 0.7266
Epoch 3/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7304
Epoch 4/500
804/804 [==============================] - 1s 955us/step - loss: 0.5539 - accuracy: 0.7307
Epoch 5/500
804/804 [==============================] - 1s 950us/step - loss: 0.5526 - accuracy: 0.7317
Epoch 6/500
804/804 [==============================] - 1s 959us/step - loss: 0.5519 - accuracy: 0.7307
Epoch 7/500
804/804 [==============================] - 1s 998us/step - loss: 0.5515 - accuracy: 0.7311
Epoch 8/500
804/804 [==============================] - 1s 995us/step - loss: 0.5507 - accuracy: 0.7321
Epoch 9/500
804/804 [==============================] - 1s 995us/step - loss: 0.5504 - accuracy: 0.7304
Epoch 10/500
804/804 [==============================] - 1s 945us/step - loss: 0.5493 - accuracy: 0.7316
Epoch 11/500
804/804 [==============================] - 1s 912us/step - loss: 0.5491 - accuracy: 0.7323
Epoch 12/500
804/804 [==============================] - 1s 938us/step - loss: 0.5490 - accuracy: 0.7311
Epoch 13/500
804/804 [==============================] - 1s 898us/step - loss: 0.5488 - accuracy: 0.7316
Epoch 14/500
804/804 [==============================] - 1s 916us/step - loss: 0.5481 - accuracy: 0.7319
Epoch 15/500
804/804 [==============================] - 1s 998us/step - loss: 0.5479 - accuracy: 0.7330
Epoch 16/500
804/804 [==============================] - 1s 981us/step - loss: 0.5474 - accuracy: 0.7328
Epoch 17/500
804/804 [==============================] - 1s 933us/step - loss: 0.5473 - accuracy: 0.7329
Epoch 18/500
804/804 [==============================] - 1s 988us/step - loss: 0.5466 - accuracy: 0.7339
Epoch 19/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7332
Epoch 20/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5462 - accuracy: 0.7334
Epoch 21/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5460 - accuracy: 0.7338
Epoch 22/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7341: 0s - loss: 0.5513
Epoch 23/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7348
Epoch 24/500
804/804 [==============================] - 1s 913us/step - loss: 0.5456 - accuracy: 0.7339
Epoch 25/500
804/804 [==============================] - 1s 904us/step - loss: 0.5450 - accuracy: 0.7345
Epoch 26/500
804/804 [==============================] - 1s 937us/step - loss: 0.5449 - accuracy: 0.7341
Epoch 27/500
804/804 [==============================] - 1s 959us/step - loss: 0.5450 - accuracy: 0.7345
Epoch 28/500
804/804 [==============================] - 1s 933us/step - loss: 0.5451 - accuracy: 0.7341
Epoch 29/500
804/804 [==============================] - 1s 988us/step - loss: 0.5447 - accuracy: 0.7344
Epoch 30/500
804/804 [==============================] - 1s 908us/step - loss: 0.5444 - accuracy: 0.7346
Epoch 31/500
804/804 [==============================] - 1s 969us/step - loss: 0.5442 - accuracy: 0.7356
Epoch 32/500
804/804 [==============================] - 1s 972us/step - loss: 0.5441 - accuracy: 0.7348
Epoch 33/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7352
Epoch 34/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7345
Epoch 35/500
804/804 [==============================] - 1s 989us/step - loss: 0.5436 - accuracy: 0.7346
Epoch 36/500
804/804 [==============================] - 1s 984us/step - loss: 0.5438 - accuracy: 0.7350
Epoch 37/500
804/804 [==============================] - 1s 924us/step - loss: 0.5439 - accuracy: 0.7358
Epoch 38/500
804/804 [==============================] - 1s 915us/step - loss: 0.5433 - accuracy: 0.7351
Epoch 39/500
804/804 [==============================] - 1s 952us/step - loss: 0.5435 - accuracy: 0.7357
Epoch 40/500
804/804 [==============================] - 1s 909us/step - loss: 0.5433 - accuracy: 0.7357
Epoch 41/500
804/804 [==============================] - 1s 863us/step - loss: 0.5435 - accuracy: 0.7358
Epoch 42/500
804/804 [==============================] - 1s 893us/step - loss: 0.5430 - accuracy: 0.7358
Epoch 43/500
804/804 [==============================] - 1s 903us/step - loss: 0.5428 - accuracy: 0.7353
Epoch 44/500
804/804 [==============================] - 1s 907us/step - loss: 0.5427 - accuracy: 0.7365
Epoch 45/500
804/804 [==============================] - 1s 924us/step - loss: 0.5427 - accuracy: 0.7358
Epoch 46/500
804/804 [==============================] - 1s 917us/step - loss: 0.5426 - accuracy: 0.7362
Epoch 47/500
804/804 [==============================] - 1s 978us/step - loss: 0.5426 - accuracy: 0.7369
Epoch 48/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7360
Epoch 49/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7364
Epoch 50/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7367
Epoch 51/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7362
Epoch 52/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7368
Epoch 53/500
804/804 [==============================] - 1s 977us/step - loss: 0.5421 - accuracy: 0.7364
Epoch 54/500
804/804 [==============================] - 1s 948us/step - loss: 0.5421 - accuracy: 0.7362
Epoch 55/500
804/804 [==============================] - 1s 980us/step - loss: 0.5421 - accuracy: 0.7364
Epoch 56/500
804/804 [==============================] - 1s 975us/step - loss: 0.5420 - accuracy: 0.7368
Epoch 57/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5422 - accuracy: 0.7361
Epoch 58/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7364
Epoch 59/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7365
Epoch 60/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7363
Epoch 61/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7369
Epoch 62/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7364: 0s - loss: 0.5398 - ac
Epoch 63/500
804/804 [==============================] - 1s 969us/step - loss: 0.5416 - accuracy: 0.7371
Epoch 64/500
804/804 [==============================] - 1s 976us/step - loss: 0.5416 - accuracy: 0.7357
Epoch 65/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7370
Epoch 66/500
804/804 [==============================] - 1s 917us/step - loss: 0.5418 - accuracy: 0.7365
Epoch 67/500
804/804 [==============================] - 1s 925us/step - loss: 0.5420 - accuracy: 0.7372
Epoch 68/500
804/804 [==============================] - 1s 932us/step - loss: 0.5419 - accuracy: 0.7365
Epoch 69/500
804/804 [==============================] - 1s 951us/step - loss: 0.5417 - accuracy: 0.7365
Epoch 70/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7363
Epoch 71/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7369
Epoch 72/500
804/804 [==============================] - 1s 945us/step - loss: 0.5415 - accuracy: 0.7369
Epoch 73/500
804/804 [==============================] - 1s 897us/step - loss: 0.5414 - accuracy: 0.7366
Epoch 74/500
804/804 [==============================] - 1s 963us/step - loss: 0.5415 - accuracy: 0.7371
Epoch 75/500
804/804 [==============================] - 1s 968us/step - loss: 0.5415 - accuracy: 0.7369
Epoch 76/500
804/804 [==============================] - 1s 920us/step - loss: 0.5410 - accuracy: 0.7376
Epoch 77/500
804/804 [==============================] - 1s 980us/step - loss: 0.5409 - accuracy: 0.7379
Epoch 78/500
804/804 [==============================] - 1s 931us/step - loss: 0.5414 - accuracy: 0.7366
Epoch 79/500

804/804 [==============================] - 1s 894us/step - loss: 0.5414 - accuracy: 0.7367
Epoch 80/500
804/804 [==============================] - 1s 883us/step - loss: 0.5412 - accuracy: 0.7368
Epoch 81/500
804/804 [==============================] - 1s 878us/step - loss: 0.5410 - accuracy: 0.7373
Epoch 82/500
804/804 [==============================] - 1s 870us/step - loss: 0.5411 - accuracy: 0.7369
Epoch 83/500
804/804 [==============================] - 1s 933us/step - loss: 0.5414 - accuracy: 0.7359
Epoch 84/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7367
Epoch 85/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7365
Epoch 86/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7374
Epoch 87/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7365
Epoch 88/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7370
Epoch 89/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7362
Epoch 90/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7377
Epoch 91/500
804/804 [==============================] - 1s 960us/step - loss: 0.5409 - accuracy: 0.7369
Epoch 92/500
804/804 [==============================] - 1s 978us/step - loss: 0.5409 - accuracy: 0.7366
Epoch 93/500
804/804 [==============================] - 1s 992us/step - loss: 0.5410 - accuracy: 0.7374
Epoch 94/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7371
Epoch 95/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7367
Epoch 96/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7376
Epoch 97/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7371
Epoch 98/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7370
Epoch 99/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7364
Epoch 100/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7370
Epoch 101/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7372
Epoch 102/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7371
Epoch 103/500
804/804 [==============================] - ETA: 0s - loss: 0.5410 - accuracy: 0.73 - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7374
Epoch 104/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7371
Epoch 105/500
804/804 [==============================] - 1s 997us/step - loss: 0.5404 - accuracy: 0.7368
Epoch 106/500
804/804 [==============================] - 1s 969us/step - loss: 0.5407 - accuracy: 0.7367
Epoch 107/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7373
Epoch 108/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7371
Epoch 109/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7372
Epoch 110/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7369
Epoch 111/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7367
Epoch 112/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7376
Epoch 113/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7370
Epoch 114/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7370
Epoch 115/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7374
Epoch 116/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7374
Epoch 117/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7367: 0s - loss: 0.5371 - accuracy:
Epoch 118/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7369
Epoch 119/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7371
Epoch 120/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7371
Epoch 121/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7368
Epoch 122/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7375
Epoch 123/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7369
Epoch 124/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7373
Epoch 125/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7372
Epoch 126/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7373
Epoch 127/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7374
Epoch 128/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7373
Epoch 129/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7369
Epoch 130/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7374
Epoch 131/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7376
Epoch 132/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7377
Epoch 133/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7374
Epoch 134/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7379
Epoch 135/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7374
Epoch 136/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7370
Epoch 137/500
804/804 [==============================] - 1s 986us/step - loss: 0.5404 - accuracy: 0.7372
Epoch 138/500
804/804 [==============================] - 1s 950us/step - loss: 0.5401 - accuracy: 0.7378
Epoch 139/500
804/804 [==============================] - 1s 962us/step - loss: 0.5401 - accuracy: 0.7373
Epoch 140/500
804/804 [==============================] - 1s 987us/step - loss: 0.5400 - accuracy: 0.7372
Epoch 141/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7369
Epoch 142/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7379
Epoch 143/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7379
Epoch 144/500
804/804 [==============================] - 1s 897us/step - loss: 0.5400 - accuracy: 0.7372
Epoch 145/500
804/804 [==============================] - 1s 936us/step - loss: 0.5399 - accuracy: 0.7374
Epoch 146/500
804/804 [==============================] - ETA: 0s - loss: 0.5404 - accuracy: 0.73 - 1s 917us/step - loss: 0.5402 - accuracy: 0.7374
Epoch 147/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7370
Epoch 148/500
804/804 [==============================] - 1s 913us/step - loss: 0.5400 - accuracy: 0.7384
Epoch 149/500
804/804 [==============================] - 1s 906us/step - loss: 0.5402 - accuracy: 0.7376
Epoch 150/500
804/804 [==============================] - 1s 925us/step - loss: 0.5400 - accuracy: 0.7369
Epoch 151/500
804/804 [==============================] - 1s 928us/step - loss: 0.5399 - accuracy: 0.7373
Epoch 152/500
804/804 [==============================] - 1s 902us/step - loss: 0.5396 - accuracy: 0.7369
Epoch 153/500
804/804 [==============================] - 1s 898us/step - loss: 0.5400 - accuracy: 0.7371
Epoch 154/500
804/804 [==============================] - 1s 890us/step - loss: 0.5398 - accuracy: 0.7379
Epoch 155/500
804/804 [==============================] - 1s 892us/step - loss: 0.5402 - accuracy: 0.7369
Epoch 156/500
804/804 [==============================] - 1s 886us/step - loss: 0.5399 - accuracy: 0.7373
Epoch 157/500

804/804 [==============================] - 1s 877us/step - loss: 0.5399 - accuracy: 0.7373
Epoch 158/500
804/804 [==============================] - 1s 872us/step - loss: 0.5400 - accuracy: 0.7373
Epoch 159/500
804/804 [==============================] - 1s 899us/step - loss: 0.5398 - accuracy: 0.7372
Epoch 160/500
804/804 [==============================] - 1s 896us/step - loss: 0.5398 - accuracy: 0.7372
Epoch 161/500
804/804 [==============================] - 1s 953us/step - loss: 0.5398 - accuracy: 0.7375
Epoch 162/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7365
Epoch 163/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7376
Epoch 164/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7374
Epoch 165/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7379
Epoch 166/500
804/804 [==============================] - 1s 973us/step - loss: 0.5399 - accuracy: 0.7368
Epoch 167/500
804/804 [==============================] - 1s 951us/step - loss: 0.5399 - accuracy: 0.7376
Epoch 168/500
804/804 [==============================] - 1s 962us/step - loss: 0.5402 - accuracy: 0.7371
Epoch 169/500
804/804 [==============================] - 1s 948us/step - loss: 0.5399 - accuracy: 0.7379
Epoch 170/500
804/804 [==============================] - 1s 998us/step - loss: 0.5395 - accuracy: 0.7375
Epoch 171/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7375
Epoch 172/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7372
Epoch 173/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7375
Epoch 174/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7376
Epoch 175/500
804/804 [==============================] - 1s 978us/step - loss: 0.5399 - accuracy: 0.7372
Epoch 176/500
804/804 [==============================] - 1s 927us/step - loss: 0.5396 - accuracy: 0.7376
Epoch 177/500
804/804 [==============================] - 1s 869us/step - loss: 0.5398 - accuracy: 0.7371
Epoch 178/500
804/804 [==============================] - 1s 846us/step - loss: 0.5398 - accuracy: 0.7378
Epoch 179/500
804/804 [==============================] - 1s 902us/step - loss: 0.5400 - accuracy: 0.7377
Epoch 180/500
804/804 [==============================] - 1s 963us/step - loss: 0.5398 - accuracy: 0.7375
Epoch 181/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7368
Epoch 182/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7371
Epoch 183/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7373
Epoch 184/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7376
Epoch 185/500
804/804 [==============================] - 1s 941us/step - loss: 0.5399 - accuracy: 0.7378
Epoch 186/500
804/804 [==============================] - 1s 883us/step - loss: 0.5398 - accuracy: 0.7378
Epoch 187/500
804/804 [==============================] - 1s 883us/step - loss: 0.5399 - accuracy: 0.7372
Epoch 188/500
804/804 [==============================] - 1s 858us/step - loss: 0.5396 - accuracy: 0.7378
Epoch 189/500
804/804 [==============================] - 1s 873us/step - loss: 0.5396 - accuracy: 0.7373
Epoch 190/500
804/804 [==============================] - 1s 867us/step - loss: 0.5395 - accuracy: 0.7372
Epoch 191/500
804/804 [==============================] - 1s 902us/step - loss: 0.5396 - accuracy: 0.7376
Epoch 192/500
804/804 [==============================] - 1s 879us/step - loss: 0.5399 - accuracy: 0.7377
Epoch 193/500
804/804 [==============================] - 1s 887us/step - loss: 0.5397 - accuracy: 0.7378
Epoch 194/500
804/804 [==============================] - 1s 964us/step - loss: 0.5397 - accuracy: 0.7378
Epoch 195/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7377
Epoch 196/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7372
Epoch 197/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7378
Epoch 198/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7374
Epoch 199/500
804/804 [==============================] - 1s 991us/step - loss: 0.5394 - accuracy: 0.7378
Epoch 200/500
804/804 [==============================] - 1s 946us/step - loss: 0.5397 - accuracy: 0.7372
Epoch 201/500
804/804 [==============================] - 1s 907us/step - loss: 0.5396 - accuracy: 0.7377
Epoch 202/500
804/804 [==============================] - 1s 933us/step - loss: 0.5395 - accuracy: 0.7379
Epoch 203/500
804/804 [==============================] - 1s 980us/step - loss: 0.5394 - accuracy: 0.7383
Epoch 204/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7376
Epoch 205/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7370
Epoch 206/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7372
Epoch 207/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7378
Epoch 208/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7378
Epoch 209/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7373
Epoch 210/500
804/804 [==============================] - 1s 945us/step - loss: 0.5396 - accuracy: 0.7369
Epoch 211/500
804/804 [==============================] - 1s 935us/step - loss: 0.5396 - accuracy: 0.7373
Epoch 212/500
804/804 [==============================] - 1s 939us/step - loss: 0.5399 - accuracy: 0.7370
Epoch 213/500
804/804 [==============================] - 1s 906us/step - loss: 0.5394 - accuracy: 0.7378
Epoch 214/500
804/804 [==============================] - 1s 882us/step - loss: 0.5394 - accuracy: 0.7373
Epoch 215/500
804/804 [==============================] - 1s 896us/step - loss: 0.5393 - accuracy: 0.7376
Epoch 216/500
804/804 [==============================] - 1s 888us/step - loss: 0.5395 - accuracy: 0.7373
Epoch 217/500
804/804 [==============================] - 1s 870us/step - loss: 0.5395 - accuracy: 0.7367
Epoch 218/500
804/804 [==============================] - 1s 863us/step - loss: 0.5393 - accuracy: 0.7376
Epoch 219/500
804/804 [==============================] - 1s 863us/step - loss: 0.5393 - accuracy: 0.7372
Epoch 220/500
804/804 [==============================] - 1s 865us/step - loss: 0.5393 - accuracy: 0.7369
Epoch 221/500
804/804 [==============================] - 1s 880us/step - loss: 0.5393 - accuracy: 0.7377
Epoch 222/500
804/804 [==============================] - 1s 903us/step - loss: 0.5394 - accuracy: 0.7371
Epoch 223/500
804/804 [==============================] - 1s 899us/step - loss: 0.5396 - accuracy: 0.7373
Epoch 224/500
804/804 [==============================] - 1s 893us/step - loss: 0.5394 - accuracy: 0.7376
Epoch 225/500
804/804 [==============================] - 1s 835us/step - loss: 0.5395 - accuracy: 0.7376
Epoch 226/500
804/804 [==============================] - 1s 969us/step - loss: 0.5393 - accuracy: 0.7381
Epoch 227/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7370
Epoch 228/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7375
Epoch 229/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7369
Epoch 230/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7375
Epoch 231/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7375
Epoch 232/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7369
Epoch 233/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 234/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7373
Epoch 235/500

804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7371
Epoch 236/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7379
Epoch 237/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7378
Epoch 238/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7370
Epoch 239/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7375
Epoch 240/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7381
Epoch 241/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7377
Epoch 242/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7377: 0s - loss: 0.5417 - accura
Epoch 243/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7372
Epoch 244/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7376
Epoch 245/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7378
Epoch 246/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7378
Epoch 247/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7375
Epoch 248/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7372
Epoch 249/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7379
Epoch 250/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7371
Epoch 251/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7379
Epoch 252/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7377
Epoch 253/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7375
Epoch 254/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7376
Epoch 255/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7376
Epoch 256/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7378
Epoch 257/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7374
Epoch 258/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7378
Epoch 259/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7375
Epoch 260/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7380
Epoch 261/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7377
Epoch 262/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7374
Epoch 263/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7377
Epoch 264/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7378
Epoch 265/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7378
Epoch 266/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7377
Epoch 267/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7376
Epoch 268/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7377
Epoch 269/500
804/804 [==============================] - 1s 900us/step - loss: 0.5392 - accuracy: 0.7370
Epoch 270/500
804/804 [==============================] - 1s 898us/step - loss: 0.5390 - accuracy: 0.7379
Epoch 271/500
804/804 [==============================] - 1s 898us/step - loss: 0.5389 - accuracy: 0.7371
Epoch 272/500
804/804 [==============================] - 1s 891us/step - loss: 0.5391 - accuracy: 0.7379
Epoch 273/500
804/804 [==============================] - 1s 902us/step - loss: 0.5388 - accuracy: 0.7380
Epoch 274/500
804/804 [==============================] - 1s 930us/step - loss: 0.5390 - accuracy: 0.7379
Epoch 275/500
804/804 [==============================] - 1s 902us/step - loss: 0.5387 - accuracy: 0.7381
Epoch 276/500
804/804 [==============================] - 1s 922us/step - loss: 0.5388 - accuracy: 0.7378
Epoch 277/500
804/804 [==============================] - 1s 927us/step - loss: 0.5391 - accuracy: 0.7377
Epoch 278/500
804/804 [==============================] - 1s 928us/step - loss: 0.5390 - accuracy: 0.7379
Epoch 279/500
804/804 [==============================] - 1s 896us/step - loss: 0.5391 - accuracy: 0.7374
Epoch 280/500
804/804 [==============================] - 1s 881us/step - loss: 0.5389 - accuracy: 0.7377
Epoch 281/500
804/804 [==============================] - 1s 876us/step - loss: 0.5389 - accuracy: 0.7378
Epoch 282/500
804/804 [==============================] - 1s 899us/step - loss: 0.5390 - accuracy: 0.7380
Epoch 283/500
804/804 [==============================] - 1s 861us/step - loss: 0.5387 - accuracy: 0.7379
Epoch 284/500
804/804 [==============================] - 1s 931us/step - loss: 0.5389 - accuracy: 0.7372
Epoch 285/500
804/804 [==============================] - 1s 958us/step - loss: 0.5388 - accuracy: 0.7376
Epoch 286/500
804/804 [==============================] - 1s 969us/step - loss: 0.5389 - accuracy: 0.7378
Epoch 287/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7381
Epoch 288/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7375
Epoch 289/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7377
Epoch 290/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7377
Epoch 291/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7373
Epoch 292/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7378
Epoch 293/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7372
Epoch 294/500
804/804 [==============================] - 1s 989us/step - loss: 0.5389 - accuracy: 0.7378
Epoch 295/500
804/804 [==============================] - 1s 892us/step - loss: 0.5389 - accuracy: 0.7379
Epoch 296/500
804/804 [==============================] - 1s 903us/step - loss: 0.5390 - accuracy: 0.7379
Epoch 297/500
804/804 [==============================] - 1s 900us/step - loss: 0.5386 - accuracy: 0.7381
Epoch 298/500
804/804 [==============================] - 1s 927us/step - loss: 0.5388 - accuracy: 0.7381
Epoch 299/500
804/804 [==============================] - 1s 907us/step - loss: 0.5388 - accuracy: 0.7376
Epoch 300/500
804/804 [==============================] - 1s 914us/step - loss: 0.5388 - accuracy: 0.7380
Epoch 301/500
804/804 [==============================] - 1s 947us/step - loss: 0.5389 - accuracy: 0.7382
Epoch 302/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7374
Epoch 303/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7376
Epoch 304/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7378
Epoch 305/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7378
Epoch 306/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7377
Epoch 307/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7379
Epoch 308/500
804/804 [==============================] - 1s 947us/step - loss: 0.5389 - accuracy: 0.7375
Epoch 309/500
804/804 [==============================] - 1s 893us/step - loss: 0.5388 - accuracy: 0.7378
Epoch 310/500
804/804 [==============================] - 1s 910us/step - loss: 0.5387 - accuracy: 0.7377
Epoch 311/500
804/804 [==============================] - 1s 902us/step - loss: 0.5389 - accuracy: 0.7381
Epoch 312/500
804/804 [==============================] - 1s 893us/step - loss: 0.5387 - accuracy: 0.7379
Epoch 313/500

804/804 [==============================] - 1s 880us/step - loss: 0.5387 - accuracy: 0.7376
Epoch 314/500
804/804 [==============================] - 1s 860us/step - loss: 0.5389 - accuracy: 0.7377
Epoch 315/500
804/804 [==============================] - 1s 878us/step - loss: 0.5390 - accuracy: 0.7376
Epoch 316/500
804/804 [==============================] - 1s 899us/step - loss: 0.5388 - accuracy: 0.7378
Epoch 317/500
804/804 [==============================] - 1s 943us/step - loss: 0.5389 - accuracy: 0.7383
Epoch 318/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7379
Epoch 319/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7377
Epoch 320/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7381
Epoch 321/500
804/804 [==============================] - 1s 909us/step - loss: 0.5387 - accuracy: 0.7378
Epoch 322/500
804/804 [==============================] - 1s 885us/step - loss: 0.5389 - accuracy: 0.7372
Epoch 323/500
804/804 [==============================] - 1s 864us/step - loss: 0.5388 - accuracy: 0.7381
Epoch 324/500
804/804 [==============================] - 1s 838us/step - loss: 0.5389 - accuracy: 0.7377
Epoch 325/500
804/804 [==============================] - 1s 856us/step - loss: 0.5389 - accuracy: 0.7378
Epoch 326/500
804/804 [==============================] - 1s 844us/step - loss: 0.5387 - accuracy: 0.7376
Epoch 327/500
804/804 [==============================] - 1s 865us/step - loss: 0.5387 - accuracy: 0.7375
Epoch 328/500
804/804 [==============================] - 1s 847us/step - loss: 0.5389 - accuracy: 0.7383
Epoch 329/500
804/804 [==============================] - 1s 877us/step - loss: 0.5387 - accuracy: 0.7384
Epoch 330/500
804/804 [==============================] - 1s 913us/step - loss: 0.5387 - accuracy: 0.7380
Epoch 331/500
804/804 [==============================] - 1s 909us/step - loss: 0.5388 - accuracy: 0.7385
Epoch 332/500
804/804 [==============================] - 1s 929us/step - loss: 0.5386 - accuracy: 0.7372
Epoch 333/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7373
Epoch 334/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7373
Epoch 335/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7376
Epoch 336/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7380
Epoch 337/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7373
Epoch 338/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7376
Epoch 339/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7378
Epoch 340/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7376
Epoch 341/500
804/804 [==============================] - 1s 840us/step - loss: 0.5386 - accuracy: 0.7386
Epoch 342/500
804/804 [==============================] - 1s 852us/step - loss: 0.5386 - accuracy: 0.7381
Epoch 343/500
804/804 [==============================] - 1s 861us/step - loss: 0.5389 - accuracy: 0.7379
Epoch 344/500
804/804 [==============================] - 1s 858us/step - loss: 0.5388 - accuracy: 0.7375
Epoch 345/500
804/804 [==============================] - 1s 839us/step - loss: 0.5387 - accuracy: 0.7377
Epoch 346/500
804/804 [==============================] - 1s 887us/step - loss: 0.5387 - accuracy: 0.7378
Epoch 347/500
804/804 [==============================] - 1s 868us/step - loss: 0.5384 - accuracy: 0.7381
Epoch 348/500
804/804 [==============================] - 1s 964us/step - loss: 0.5386 - accuracy: 0.7379
Epoch 349/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 350/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7381
Epoch 351/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7381
Epoch 352/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7383
Epoch 353/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 354/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7379
Epoch 355/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7380
Epoch 356/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7374
Epoch 357/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7379
Epoch 358/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7382
Epoch 359/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7379
Epoch 360/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 361/500
804/804 [==============================] - 1s 963us/step - loss: 0.5387 - accuracy: 0.7379
Epoch 362/500
804/804 [==============================] - 1s 953us/step - loss: 0.5387 - accuracy: 0.7374
Epoch 363/500
804/804 [==============================] - 1s 954us/step - loss: 0.5382 - accuracy: 0.7386
Epoch 364/500
804/804 [==============================] - 1s 916us/step - loss: 0.5388 - accuracy: 0.7378
Epoch 365/500
804/804 [==============================] - 1s 970us/step - loss: 0.5386 - accuracy: 0.7376
Epoch 366/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7378
Epoch 367/500
804/804 [==============================] - 1s 891us/step - loss: 0.5384 - accuracy: 0.7379
Epoch 368/500
804/804 [==============================] - 1s 910us/step - loss: 0.5386 - accuracy: 0.7381
Epoch 369/500
804/804 [==============================] - 1s 898us/step - loss: 0.5386 - accuracy: 0.7384
Epoch 370/500
804/804 [==============================] - 1s 890us/step - loss: 0.5386 - accuracy: 0.7378
Epoch 371/500
804/804 [==============================] - 1s 896us/step - loss: 0.5386 - accuracy: 0.7378
Epoch 372/500
804/804 [==============================] - 1s 896us/step - loss: 0.5386 - accuracy: 0.7376
Epoch 373/500
804/804 [==============================] - 1s 919us/step - loss: 0.5384 - accuracy: 0.7377
Epoch 374/500
804/804 [==============================] - 1s 922us/step - loss: 0.5387 - accuracy: 0.7381
Epoch 375/500
804/804 [==============================] - 1s 908us/step - loss: 0.5384 - accuracy: 0.7381
Epoch 376/500
804/804 [==============================] - 1s 914us/step - loss: 0.5386 - accuracy: 0.7377
Epoch 377/500
804/804 [==============================] - 1s 917us/step - loss: 0.5386 - accuracy: 0.7375
Epoch 378/500
804/804 [==============================] - 1s 892us/step - loss: 0.5386 - accuracy: 0.7382
Epoch 379/500
804/804 [==============================] - 1s 921us/step - loss: 0.5386 - accuracy: 0.7378
Epoch 380/500
804/804 [==============================] - 1s 890us/step - loss: 0.5386 - accuracy: 0.7383
Epoch 381/500
804/804 [==============================] - 1s 893us/step - loss: 0.5385 - accuracy: 0.7379
Epoch 382/500
804/804 [==============================] - 1s 878us/step - loss: 0.5387 - accuracy: 0.7381
Epoch 383/500
804/804 [==============================] - 1s 898us/step - loss: 0.5383 - accuracy: 0.7378
Epoch 384/500
804/804 [==============================] - 1s 942us/step - loss: 0.5385 - accuracy: 0.7378
Epoch 385/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7374
Epoch 386/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7379
Epoch 387/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7384
Epoch 388/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7385
Epoch 389/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7379
Epoch 390/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7380
Epoch 391/500

804/804 [==============================] - 1s 941us/step - loss: 0.5385 - accuracy: 0.7377
Epoch 392/500
804/804 [==============================] - 1s 890us/step - loss: 0.5382 - accuracy: 0.7379
Epoch 393/500
804/804 [==============================] - 1s 888us/step - loss: 0.5383 - accuracy: 0.7379
Epoch 394/500
804/804 [==============================] - 1s 922us/step - loss: 0.5386 - accuracy: 0.7378
Epoch 395/500
804/804 [==============================] - 1s 920us/step - loss: 0.5385 - accuracy: 0.7384
Epoch 396/500
804/804 [==============================] - 1s 912us/step - loss: 0.5387 - accuracy: 0.7381
Epoch 397/500
804/804 [==============================] - 1s 926us/step - loss: 0.5383 - accuracy: 0.7379
Epoch 398/500
804/804 [==============================] - 1s 889us/step - loss: 0.5386 - accuracy: 0.7378
Epoch 399/500
804/804 [==============================] - 1s 926us/step - loss: 0.5385 - accuracy: 0.7383
Epoch 400/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7377
Epoch 401/500
804/804 [==============================] - 1s 936us/step - loss: 0.5386 - accuracy: 0.7379
Epoch 402/500
804/804 [==============================] - 1s 962us/step - loss: 0.5385 - accuracy: 0.7380
Epoch 403/500
804/804 [==============================] - 1s 928us/step - loss: 0.5385 - accuracy: 0.7378
Epoch 404/500
804/804 [==============================] - 1s 887us/step - loss: 0.5382 - accuracy: 0.7381
Epoch 405/500
804/804 [==============================] - 1s 910us/step - loss: 0.5383 - accuracy: 0.7376
Epoch 406/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7379
Epoch 407/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7380
Epoch 408/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7381
Epoch 409/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7383
Epoch 410/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7375
Epoch 411/500
804/804 [==============================] - 1s 917us/step - loss: 0.5385 - accuracy: 0.7380
Epoch 412/500
804/804 [==============================] - 1s 867us/step - loss: 0.5384 - accuracy: 0.7381
Epoch 413/500
804/804 [==============================] - 1s 857us/step - loss: 0.5383 - accuracy: 0.7380
Epoch 414/500
804/804 [==============================] - 1s 857us/step - loss: 0.5384 - accuracy: 0.7379
Epoch 415/500
804/804 [==============================] - 1s 839us/step - loss: 0.5382 - accuracy: 0.7384
Epoch 416/500
804/804 [==============================] - 1s 876us/step - loss: 0.5384 - accuracy: 0.7380
Epoch 417/500
804/804 [==============================] - 1s 867us/step - loss: 0.5384 - accuracy: 0.7376
Epoch 418/500
804/804 [==============================] - 1s 875us/step - loss: 0.5383 - accuracy: 0.7385
Epoch 419/500
804/804 [==============================] - 1s 894us/step - loss: 0.5384 - accuracy: 0.7378
Epoch 420/500
804/804 [==============================] - 1s 891us/step - loss: 0.5383 - accuracy: 0.7378
Epoch 421/500
804/804 [==============================] - 1s 862us/step - loss: 0.5383 - accuracy: 0.7384
Epoch 422/500
804/804 [==============================] - 1s 836us/step - loss: 0.5386 - accuracy: 0.7379
Epoch 423/500
804/804 [==============================] - 1s 886us/step - loss: 0.5383 - accuracy: 0.7372
Epoch 424/500
804/804 [==============================] - 1s 949us/step - loss: 0.5385 - accuracy: 0.7381
Epoch 425/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7382
Epoch 426/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7381
Epoch 427/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7386
Epoch 428/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7379
Epoch 429/500
804/804 [==============================] - 1s 904us/step - loss: 0.5384 - accuracy: 0.7382
Epoch 430/500
804/804 [==============================] - 1s 881us/step - loss: 0.5382 - accuracy: 0.7377
Epoch 431/500
804/804 [==============================] - 1s 857us/step - loss: 0.5381 - accuracy: 0.7379
Epoch 432/500
804/804 [==============================] - 1s 893us/step - loss: 0.5382 - accuracy: 0.7381
Epoch 433/500
804/804 [==============================] - 1s 892us/step - loss: 0.5383 - accuracy: 0.7376
Epoch 434/500
804/804 [==============================] - 1s 878us/step - loss: 0.5383 - accuracy: 0.7381
Epoch 435/500
804/804 [==============================] - 1s 927us/step - loss: 0.5383 - accuracy: 0.7381
Epoch 436/500
804/804 [==============================] - 1s 936us/step - loss: 0.5384 - accuracy: 0.7380
Epoch 437/500
804/804 [==============================] - 1s 943us/step - loss: 0.5383 - accuracy: 0.7377
Epoch 438/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7384
Epoch 439/500
804/804 [==============================] - 1s 971us/step - loss: 0.5382 - accuracy: 0.7380
Epoch 440/500
804/804 [==============================] - 1s 929us/step - loss: 0.5381 - accuracy: 0.7384
Epoch 441/500
804/804 [==============================] - 1s 902us/step - loss: 0.5383 - accuracy: 0.7379
Epoch 442/500
804/804 [==============================] - 1s 906us/step - loss: 0.5382 - accuracy: 0.7376
Epoch 443/500
804/804 [==============================] - 1s 880us/step - loss: 0.5385 - accuracy: 0.7376
Epoch 444/500
804/804 [==============================] - 1s 898us/step - loss: 0.5384 - accuracy: 0.7380
Epoch 445/500
804/804 [==============================] - 1s 971us/step - loss: 0.5383 - accuracy: 0.7382
Epoch 446/500
804/804 [==============================] - 1s 933us/step - loss: 0.5384 - accuracy: 0.7382
Epoch 447/500
804/804 [==============================] - 1s 959us/step - loss: 0.5383 - accuracy: 0.7383
Epoch 448/500
804/804 [==============================] - 1s 948us/step - loss: 0.5383 - accuracy: 0.7376
Epoch 449/500
804/804 [==============================] - 1s 977us/step - loss: 0.5380 - accuracy: 0.7383
Epoch 450/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7384
Epoch 451/500
804/804 [==============================] - 1s 981us/step - loss: 0.5384 - accuracy: 0.7381
Epoch 452/500
804/804 [==============================] - 1s 887us/step - loss: 0.5383 - accuracy: 0.7379
Epoch 453/500
804/804 [==============================] - 1s 914us/step - loss: 0.5383 - accuracy: 0.7381
Epoch 454/500
804/804 [==============================] - 1s 916us/step - loss: 0.5385 - accuracy: 0.7382
Epoch 455/500
804/804 [==============================] - 1s 888us/step - loss: 0.5384 - accuracy: 0.7383
Epoch 456/500
804/804 [==============================] - 1s 897us/step - loss: 0.5383 - accuracy: 0.7380
Epoch 457/500
804/804 [==============================] - 1s 904us/step - loss: 0.5382 - accuracy: 0.7374
Epoch 458/500
804/804 [==============================] - 1s 841us/step - loss: 0.5383 - accuracy: 0.7374
Epoch 459/500
804/804 [==============================] - 1s 863us/step - loss: 0.5381 - accuracy: 0.7387
Epoch 460/500
804/804 [==============================] - 1s 895us/step - loss: 0.5384 - accuracy: 0.7383
Epoch 461/500
804/804 [==============================] - 1s 867us/step - loss: 0.5382 - accuracy: 0.7381
Epoch 462/500
804/804 [==============================] - 1s 891us/step - loss: 0.5383 - accuracy: 0.7389
Epoch 463/500
804/804 [==============================] - 1s 879us/step - loss: 0.5383 - accuracy: 0.7378
Epoch 464/500
804/804 [==============================] - 1s 868us/step - loss: 0.5383 - accuracy: 0.7382
Epoch 465/500
804/804 [==============================] - 1s 897us/step - loss: 0.5379 - accuracy: 0.7387
Epoch 466/500
804/804 [==============================] - 1s 878us/step - loss: 0.5381 - accuracy: 0.7381
Epoch 467/500
804/804 [==============================] - 1s 919us/step - loss: 0.5382 - accuracy: 0.7383
Epoch 468/500
804/804 [==============================] - 1s 899us/step - loss: 0.5384 - accuracy: 0.7386
Epoch 469/500

804/804 [==============================] - 1s 873us/step - loss: 0.5383 - accuracy: 0.7383
Epoch 470/500
804/804 [==============================] - 1s 884us/step - loss: 0.5380 - accuracy: 0.7385
Epoch 471/500
804/804 [==============================] - 1s 916us/step - loss: 0.5383 - accuracy: 0.7378
Epoch 472/500
804/804 [==============================] - 1s 975us/step - loss: 0.5382 - accuracy: 0.7388
Epoch 473/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7384
Epoch 474/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7382
Epoch 475/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7384
Epoch 476/500
804/804 [==============================] - 1s 963us/step - loss: 0.5384 - accuracy: 0.7381
Epoch 477/500
804/804 [==============================] - 1s 892us/step - loss: 0.5382 - accuracy: 0.7385
Epoch 478/500
804/804 [==============================] - 1s 869us/step - loss: 0.5383 - accuracy: 0.7384
Epoch 479/500
804/804 [==============================] - 1s 883us/step - loss: 0.5383 - accuracy: 0.7382
Epoch 480/500
804/804 [==============================] - 1s 901us/step - loss: 0.5382 - accuracy: 0.7384
Epoch 481/500
804/804 [==============================] - 1s 947us/step - loss: 0.5384 - accuracy: 0.7381
Epoch 482/500
804/804 [==============================] - 1s 982us/step - loss: 0.5382 - accuracy: 0.7383
Epoch 483/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7382
Epoch 484/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7379
Epoch 485/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7387
Epoch 486/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7378
Epoch 487/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7379
Epoch 488/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7386: 0s - loss: 0
Epoch 489/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7387
Epoch 490/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7384
Epoch 491/500
804/804 [==============================] - 1s 975us/step - loss: 0.5383 - accuracy: 0.7385
Epoch 492/500
804/804 [==============================] - 1s 918us/step - loss: 0.5382 - accuracy: 0.7381
Epoch 493/500
804/804 [==============================] - 1s 895us/step - loss: 0.5383 - accuracy: 0.7379
Epoch 494/500
804/804 [==============================] - 1s 913us/step - loss: 0.5383 - accuracy: 0.7385
Epoch 495/500
804/804 [==============================] - 1s 963us/step - loss: 0.5384 - accuracy: 0.7380
Epoch 496/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7388
Epoch 497/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7389
Epoch 498/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7373
Epoch 499/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7388
Epoch 500/500
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7380

In [35]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5536 - accuracy: 0.7271
Loss: 0.5536333918571472, Accuracy: 0.7271137237548828

In [36]:
#Attempt #3: add more hidden layers (2)

In [37]:
#import dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#import and read csv
import pandas as pd
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [38]:
#drop the non-beneficial ID columns, 'EIN' and "NAME"
application_df = application_df.drop(columns=["NAME"])
application_df.head()

,EIN,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [39]:
#determine the number of unique values in each column

#create categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes =="object"].index.tolist()

#check the number of unique values in each column
application_df[application_cat].nunique()

APPLICATION_TYPE          17
AFFILIATION                6
CLASSIFICATION            71
USE_CASE                   5
ORGANIZATION               4
INCOME_AMT                 9
SPECIAL_CONSIDERATIONS     2
dtype: int64

In [40]:
#look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [41]:
#choose a cutoff value and create a list of application types to be replaced 
#use the variable name 'application_types_to_replace'
application_types_to_replace = list(application_type_counts[application_type_counts<500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [42]:
#replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app, "Other")

#check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [43]:
# look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [44]:
#choose a cutoff value and create a list of classifications to be replaced
#use the variable name 'classifications_to_replace'
classifications_to_replace = list(cleaned_class_counts[cleaned_class_counts<100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256']

In [45]:
#replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")
    
#make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      643
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: CLASSIFICATION, dtype: int64

In [46]:
#convert categorical data to numeric data with 'pd.get_dummies'
application_df = pd.get_dummies(application_df, dtype=float)
application_df

,EIN,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,10520599,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,10531628,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,10547893,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,10553066,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,10556103,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,996010315,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,996012607,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,996015768,1,5000,1,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,996086871,1,36500179,0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [47]:
#split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"], 1).values

#split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

C:\Users\jenna\AppData\Local\Temp/ipykernel_19864/3545267911.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  X = application_df.drop(["IS_SUCCESSFUL"], 1).values

In [48]:
#create a StandardScaler instances
scaler = StandardScaler()

#fit the StandardScaler
X_scaler = scaler.fit(X_train)

#Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [49]:
#define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 5
hidden_nodes_layer3 = 4
hidden_nodes_layer4 = 7

nn = tf.keras.models.Sequential()

#first hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

#second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

#third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))

#fourth hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))


#output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

#check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_6 (Dense)              (None, 8)                 616
_________________________________________________________________
dense_7 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_8 (Dense)              (None, 4)                 24
_________________________________________________________________
dense_9 (Dense)              (None, 7)                 35
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 8
=================================================================
Total params: 728
Trainable params: 728
Non-trainable params: 0
_________________________________________________________________

In [50]:
#compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [51]:
#train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 1s 1ms/step - loss: 0.6067 - accuracy: 0.7038
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5692 - accuracy: 0.7278
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5594 - accuracy: 0.7309
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5547 - accuracy: 0.7313
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5519 - accuracy: 0.7336
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7331
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7321
Epoch 8/100
804/804 [==============================] - 1s 991us/step - loss: 0.5475 - accuracy: 0.7342
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7324
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7327
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7341
Epoch 12/100
804/804 [==============================] - 1s 993us/step - loss: 0.5459 - accuracy: 0.7324
Epoch 13/100
804/804 [==============================] - 1s 956us/step - loss: 0.5451 - accuracy: 0.7339
Epoch 14/100
804/804 [==============================] - 1s 958us/step - loss: 0.5452 - accuracy: 0.7340
Epoch 15/100
804/804 [==============================] - 1s 987us/step - loss: 0.5448 - accuracy: 0.7333
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7343
Epoch 17/100
804/804 [==============================] - 1s 994us/step - loss: 0.5449 - accuracy: 0.7341
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5442 - accuracy: 0.7352
Epoch 19/100
804/804 [==============================] - 1s 1000us/step - loss: 0.5439 - accuracy: 0.7364
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7346
Epoch 21/100
804/804 [==============================] - 1s 941us/step - loss: 0.5441 - accuracy: 0.7364
Epoch 22/100
804/804 [==============================] - 1s 974us/step - loss: 0.5439 - accuracy: 0.7345
Epoch 23/100
804/804 [==============================] - 1s 954us/step - loss: 0.5435 - accuracy: 0.7369
Epoch 24/100
804/804 [==============================] - 1s 947us/step - loss: 0.5435 - accuracy: 0.7341
Epoch 25/100
804/804 [==============================] - 1s 960us/step - loss: 0.5431 - accuracy: 0.7358
Epoch 26/100
804/804 [==============================] - 1s 954us/step - loss: 0.5433 - accuracy: 0.7345
Epoch 27/100
804/804 [==============================] - 1s 964us/step - loss: 0.5433 - accuracy: 0.7362
Epoch 28/100
804/804 [==============================] - 1s 945us/step - loss: 0.5428 - accuracy: 0.7345
Epoch 29/100
804/804 [==============================] - 1s 990us/step - loss: 0.5430 - accuracy: 0.7351
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7351
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7360
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7362
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7360
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5420 - accuracy: 0.7352
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7371
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7363
Epoch 37/100
804/804 [==============================] - 1s 952us/step - loss: 0.5419 - accuracy: 0.7367
Epoch 38/100
804/804 [==============================] - 1s 939us/step - loss: 0.5415 - accuracy: 0.7368
Epoch 39/100
804/804 [==============================] - 1s 919us/step - loss: 0.5415 - accuracy: 0.7366
Epoch 40/100
804/804 [==============================] - 1s 904us/step - loss: 0.5414 - accuracy: 0.7364
Epoch 41/100
804/804 [==============================] - 1s 925us/step - loss: 0.5423 - accuracy: 0.7355
Epoch 42/100
804/804 [==============================] - 1s 967us/step - loss: 0.5418 - accuracy: 0.7365
Epoch 43/100
804/804 [==============================] - 1s 962us/step - loss: 0.5412 - accuracy: 0.7374
Epoch 44/100
804/804 [==============================] - 1s 923us/step - loss: 0.5410 - accuracy: 0.7363
Epoch 45/100
804/804 [==============================] - 1s 943us/step - loss: 0.5412 - accuracy: 0.7374
Epoch 46/100
804/804 [==============================] - 1s 955us/step - loss: 0.5409 - accuracy: 0.7360
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7372
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7373
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7365
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7374
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7400
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7376
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7371
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7373
Epoch 55/100
804/804 [==============================] - 1s 918us/step - loss: 0.5409 - accuracy: 0.7364
Epoch 56/100
804/804 [==============================] - 1s 941us/step - loss: 0.5407 - accuracy: 0.7365
Epoch 57/100
804/804 [==============================] - 1s 984us/step - loss: 0.5409 - accuracy: 0.7365
Epoch 58/100
804/804 [==============================] - 1s 945us/step - loss: 0.5400 - accuracy: 0.7368
Epoch 59/100
804/804 [==============================] - 1s 946us/step - loss: 0.5405 - accuracy: 0.7383
Epoch 60/100
804/804 [==============================] - 1s 966us/step - loss: 0.5401 - accuracy: 0.7366
Epoch 61/100
804/804 [==============================] - 1s 975us/step - loss: 0.5410 - accuracy: 0.7360
Epoch 62/100
804/804 [==============================] - 1s 956us/step - loss: 0.5405 - accuracy: 0.7369
Epoch 63/100
804/804 [==============================] - 1s 944us/step - loss: 0.5407 - accuracy: 0.7358
Epoch 64/100
804/804 [==============================] - 1s 943us/step - loss: 0.5400 - accuracy: 0.7382
Epoch 65/100
804/804 [==============================] - 1s 970us/step - loss: 0.5405 - accuracy: 0.7357
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7364
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7373
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7375
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7378
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 71/100
804/804 [==============================] - 1s 983us/step - loss: 0.5402 - accuracy: 0.7365
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7376
Epoch 73/100
804/804 [==============================] - 1s 987us/step - loss: 0.5400 - accuracy: 0.7381
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5400 - accuracy: 0.7378
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7369: 0s - loss: 0.5392
Epoch 76/100
804/804 [==============================] - 1s 992us/step - loss: 0.5399 - accuracy: 0.7374
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 78/100
804/804 [==============================] - 1s 962us/step - loss: 0.5402 - accuracy: 0.7376
Epoch 79/100
804/804 [==============================] - 1s 962us/step - loss: 0.5402 - accuracy: 0.7373
Epoch 80/100

804/804 [==============================] - 1s 947us/step - loss: 0.5398 - accuracy: 0.7379
Epoch 81/100
804/804 [==============================] - 1s 970us/step - loss: 0.5395 - accuracy: 0.7381
Epoch 82/100
804/804 [==============================] - 1s 950us/step - loss: 0.5400 - accuracy: 0.7380
Epoch 83/100
804/804 [==============================] - 1s 957us/step - loss: 0.5399 - accuracy: 0.7371
Epoch 84/100
804/804 [==============================] - 1s 970us/step - loss: 0.5401 - accuracy: 0.7382
Epoch 85/100
804/804 [==============================] - 1s 947us/step - loss: 0.5396 - accuracy: 0.7379
Epoch 86/100
804/804 [==============================] - 1s 957us/step - loss: 0.5396 - accuracy: 0.7379
Epoch 87/100
804/804 [==============================] - 1s 947us/step - loss: 0.5396 - accuracy: 0.7364
Epoch 88/100
804/804 [==============================] - 1s 957us/step - loss: 0.5400 - accuracy: 0.7388
Epoch 89/100
804/804 [==============================] - 1s 994us/step - loss: 0.5397 - accuracy: 0.7374
Epoch 90/100
804/804 [==============================] - 1s 989us/step - loss: 0.5400 - accuracy: 0.7374
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7374
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7379
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7378
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7380
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7375
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7381
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7367
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7383

In [52]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5530 - accuracy: 0.7272
Loss: 0.5530438423156738, Accuracy: 0.7272303104400635

In [53]:
#export our model to HDF5 file
fit_model = fit_model.save('AlphabetSoupCharity_Optimization.h5')

AttributeError: 'History' object has no attribute 'save'